name: CodeSolid

description:  Just another CodeSolid Description

markdown: redcarpet

pygments: false

encoding: utf-8

include: ['_pages']
relative_permalinks: false

baseurl: "https://codesolid.github.io/"

post:
  template: templates/_post.txt
  extension: md

editor: C:\apps\SublimeText3\sublime_text.exe
