name: CodeSolid

description:  Just another CodeSolid Description

markdown: redcarpet

pygments: false

encoding: utf-8

include: ['_pages']
relative_permalinks: false

url: "https://codesolid.github.io"