name: CodeSolid

description:  Test Automation and Software Development Blog

meta_description: "CodeSolid is a test automation services company located in Northern California.  We're a small but focused team of talented test automation professionals who can help you quickly move your test automation effort to completion."

markdown: redcarpet

pygments: false

encoding: utf-8

include: ['_pages', '_goalboost_testplan']

relative_permalinks: false

permalink: /:title

baseurl: "http://codesolid.com/"

post:
  template: templates/_post.txt
  extension: md

editor: C:\apps\SublimeText3\sublime_text.exe

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      author:  "John Lockwood"

paginate: 12
paginate_path: "blog/page:num"
