git rm assets
git rm css
git rm images
git rm js
git rm test
git rm _assets
git rm _includes
git rm _layouts
git rm _pages
git rm _plugins
git rm _posts
git rm blog.html
git rm delme.bat
git rm dumbindex.md
git rm index.html
git rm index2.md
git rm Rakefile
git rm README.md
git rm _config.yml
